#!/usr/bin/env python3
"""Regression test for the Toyota reachability defect.

`ks_decodeToyota` fired on 12 foreign captures -- Ford, Tesla, Kia, VW -- while decoding
NONE of its own 62 Toyota/Lexus captures. Two causes, both measured:

  1. The dispatch guard was an inverted ceiling. `ratio<=2.5` (and `ratio<=3.0` on the
     Ch-B path) admitted the aliased population and excluded the brand the decoder
     serves. A real Toyota capture that contains data measures ratio 6.6-13.2, because
     the data region mixes 1T and 2T HI pulses with long inter-bit LO gaps; the
     equal-width preamble collapses toward 1.0. The foreign files it fired on measure
     ~2.0. The guard is now a floor of 3.5.

  2. The preamble minimum was 3, against this decoder's own documented 8. Only 2 of 64
     Toyota/Lexus captures actually reach 8 pairs, so raising it does not cost own-brand
     coverage today, and it cuts the foreign hits from 8 to 5.

Because the failure was reachability, this test asserts the DISPATCH CONDITION as well as
the decode, so a future edit cannot make it pass by moving the decoder further out of
reach. It runs the shipped predicate and the shipped decoder, extracted verbatim.

Run: python3 test_toyota_reachability.py
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKETCH = HERE / "FOBworks_for_SGP.ino"
CORPUS = HERE / "research" / "sources" / "corpus_automotive_subghz"

src = SKETCH.read_text(encoding="utf-8")


def block(marker: str) -> str:
    """Definition starting at `marker`, brace-matched.

    Skips forward declarations (marker lines ending in ';' before the '{'),
    which sit above the definitions since the N10 consensus work — otherwise a
    decl would make the brace scan start inside the NEXT declaration.
    """
    pos = 0
    while True:
        i = src.index(marker, pos)
        i = src.rindex("\n", 0, i) + 1
        j = src.index("{", i)
        semi = src.find(";", i, j)
        if semi < 0:
            break                     # a real definition: '{' before any ';'
        pos = semi + 1                # was a declaration; take the next match
    depth, k = 0, j
    while k < len(src):
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    return src[i : k + 1] + "\n"


# ── Static assertions on the two fix points ─────────────────────────────────
assert "if(!decoded&&te_toy&&ratio>=3.5f){" in src, \
    "Toyota primary dispatch must gate on ratio>=3.5, not a <=2.5 ceiling"
assert "if(!decoded&&toyotaB&&te_toy&&ratio<=3.0f){" in src, \
    "the Ch-B soft-ID must keep its <=3.0 ceiling; it labels ambiguous signals by design"
assert src.count("if(pc<8) continue;") >= 1, \
    "ks_decodeToyota must require >=8 preamble pairs"
# The inverted form must be gone.
assert "te_toy&&ratio<=2.5f" not in src, "the inverted ratio<=2.5 ceiling is still present"

PARTS = [
    "// Auto-generated by test_toyota_reachability.py - extracted verbatim from\n"
    "// FOBworks_for_SGP.ino.\n"
    "#include <stdio.h>\n"
    "#include <stdint.h>\n"
    "#include <stdbool.h>\n"
    "#include <string.h>\n"
    "#include <stdlib.h>\n"
    "#include <math.h>\n"
    "#define CAP_SZ 512\n",
]
for fn in ("static bool ks_km2(", "static inline bool ks_inR(", "static bool ks_decodeToyota("):
    PARTS.append(block(fn))

PARTS.append(r'''
static int loadPulses(const char* p,uint16_t* o,int cap,double* mhz){
  FILE* f=fopen(p,"r"); if(!f) return -1;
  static char ln[1<<20]; int n=0; double m=0;
  while(fgets(ln,sizeof ln,f)){
    if(!strncmp(ln,"Frequency:",10)){ m=strtod(ln+10,NULL)/1e6; continue; }
    if(strncmp(ln,"RAW_Data:",9)) continue;
    char* q=ln+9;
    while(*q&&n<cap){
      while(*q==' '||*q=='\t'||*q=='\r'||*q=='\n') q++;
      if(!*q) break;
      char* e; long v=strtol(q,&e,10); if(e==q) break; q=e;
      o[n++]=(uint16_t)(v<0?-v:v);
    }
  }
  fclose(f); *mhz=m; return n;
}

int main(int argc,char** argv){
  static uint16_t cap[4096];
  static uint32_t B[CAP_SZ];
  double mhz=0; int fails=0;
  printf("file,ratio,cA,te_toy,reachable,decoded,sn\n");
  for(int i=1;i<argc;i++){
    int rn=loadPulses(argv[i],cap,4096,&mhz);
    if(rn<32){ printf("%s,LOADFAIL\n",argv[i]); continue; }
    int n=(rn>CAP_SZ)?CAP_SZ:rn;
    for(int k=0;k<n;k++) B[k]=cap[k];
    static uint32_t kb[CAP_SZ]; int kn=0;
    for(int k=0;k<n;k++) if(B[k]<=5000) kb[kn++]=B[k];
    uint32_t cA=0,cB=0;
    ks_km2(kn>=6?kb:B, kn>=6?kn:n, cA, cB);
    float ratio=(cA>0)?(float)cB/(float)cA:0.f;
    bool tA=(mhz>=311.5&&mhz<=313.5), tB=(mhz>=313.8&&mhz<=315.5);
    bool te_toy=((tA||tB)&&cA>=150&&cA<=700);
    /* the two shipped dispatch conditions, verbatim */
    bool reachable = (te_toy && ratio>=3.5f);          /* primary dispatch */
    uint32_t sn=0; uint8_t bt=0; uint16_t ct=0;
    int dec=0;
    if(reachable) dec = ks_decodeToyota(B,n,sn,bt,ct) ? 1 : 0;
    printf("%s,%.3f,%u,%d,%d,%d,0x%06lX\n",argv[i],ratio,cA,(int)te_toy,
           (int)reachable,dec,(unsigned long)sn);
  }
  (void)fails;
  return 0;
}
''')

HARNESS = "".join(PARTS)

# The two Toyota Camry captures the decoder resolves, plus the foreign files it fired on
# before the fix. Own-brand files are asserted to be reachable; foreign files are asserted
# to be either unreachable or not decoded.
OWN = [
    "Asian/Lexus_Toyota/Toyota_Camry_l2_u2_t2_p2.sub",
    "Asian/Toyota/Camry 2019/19_toyota_camry_l2_u2_t2_p2.sub",
]
# A representative own-brand capture that should at least be REACHABLE now (the previous
# ceiling excluded it), whatever the data stage does with it.
OWN_REACHABLE = [
    "Asian/Toyota/Tundra 2011/Toyota_tundra_2011.sub",
    "Asian/Toyota/RAV4 2023/23_toyota_rav4_l2_ul2_t2_p2.sub",
    "Asian/Toyota/Tacoma/18_toyota_tacoma_l2_ul2_p2.sub",
]
FOREIGN_WAS = [
    "American/Tesla/Tesla_315MHz_AM650_Tesla-Long.sub",
    "Asian/Hyundai_Kia_Genesis/Kia_V3_N1_RAW.sub",
    "Asian/Hyundai_Kia_Genesis/Kia_4_5cl_5op_5tr.sub",
    "European/VW_Audi_Skoda_Seat/vw_atlas_l2_u2_t2_rs_2.sub",
]


def main() -> int:
    fails = []
    files = [CORPUS / f for f in OWN + OWN_REACHABLE + FOREIGN_WAS]
    missing = [str(f) for f in files if not f.is_file()]
    if missing:
        print("note: corpus files absent; cannot run", file=sys.stderr)
        for m in missing:
            print(f"      {m}", file=sys.stderr)
        return 2

    with tempfile.TemporaryDirectory() as td:
        wd = Path(td)
        cpp = wd / "t.cpp"
        cpp.write_text(HARNESS, encoding="utf-8")
        exe = wd / "t"
        cc = shutil.which("c++") or shutil.which("clang++") or "c++"
        r = subprocess.run([cc, "-O1", "-std=c++17", "-w", str(cpp), "-o", str(exe)],
                           capture_output=True, text=True)
        if r.returncode != 0:
            print("harness compile failed:\n" + r.stderr[:3000], file=sys.stderr)
            return 2
        out = subprocess.run([str(exe), *[str(f) for f in files]],
                             capture_output=True, text=True)
        if out.returncode != 0:
            print(out.stdout, out.stderr, file=sys.stderr)
            return 1

    rows = {}
    for ln in out.stdout.strip().splitlines()[1:]:
        p = ln.split(",")
        if len(p) != 7:
            continue
        rows[Path(p[0]).name] = dict(ratio=float(p[1]), cA=int(p[2]), te=int(p[3]),
                                     reach=int(p[4]), dec=int(p[5]), sn=p[6])

    def show(label, names, want_reach, want_dec=None):
        print(f"\n{label}")
        for nm in names:
            r = rows.get(Path(nm).name)
            if not r:
                fails.append(f"{Path(nm).name}: no result")
                continue
            print(f"  {Path(nm).name:52} ratio={r['ratio']:6.2f} te_toy={r['te']} "
                  f"reachable={r['reach']} decoded={r['dec']} sn={r['sn']}")
            if want_reach and not r["reach"]:
                fails.append(f"{Path(nm).name}: not reachable (ratio {r['ratio']})")
            if want_reach is False and r["reach"] and r["dec"]:
                fails.append(f"{Path(nm).name}: foreign file still decodes")
            if want_dec is not None and r["dec"] != want_dec:
                fails.append(f"{Path(nm).name}: decoded={r['dec']}, expected {want_dec}")

    show("own-brand, must be REACHABLE (the old <=2.5 ceiling excluded these):",
         OWN_REACHABLE, want_reach=True)
    show("own-brand, must DECODE:", OWN, want_reach=True, want_dec=1)
    show("foreign files the old guard let through:", FOREIGN_WAS, want_reach=None)

    print()
    if fails:
        print(f"FAIL ({len(fails)}):")
        for f in fails:
            print(f"  - {f}")
        return 1
    print("Toyota reachability: ratio floor and preamble minimum verified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
